### ISSUE TITLE
New starter submission

### ISSUE THREAD

**Issue by swelect** [forestryio/forestry.io#159]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry:

```
name: # name of your starter 
preview:# URL of your starter live preview 
  image: # Thumbnail 
  versions:
  - name: # SSG name (Gatsby, Gridsome, Hugo, Jekyll, VuePress, Next, Nuxt, etc.)
    repo: # public repo URL
    branch: (optional)
  textline: # Short description (blog, landing page, documentation, portfolio)
```

### Submission checklist 
- [ ] Import is complete
- [ ] Sidebar sections are visible 
- [ ] Media upload folder and public path are defined
- [ ] Instant Previews are working
