### ISSUE TITLE
New starter submission

### ISSUE THREAD

**Issue by LukaszBloszyk** [forestryio/forestry.io#167]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry:

```
name: # name of your starter 
preview:# URL of your starter live preview 
image: # Thumbnail URL
author: # name of the starter's author
  versions:
  - name: # SSG name (Gatsby, Gridsome, Hugo, Jekyll, VuePress, Next, Nuxt, etc.)
    repo: # public repo URL (https://github.com/username/repo
    branch: (optional) # e.g. forestry
  textline: # short description (blog, landing page, documentation, portfolio)
```

### Submission checklist 

Make sure to setup up things in Forestry:

- [ ] Import is complete 
- [ ] Sidebar sections are visible 
- [ ] Media upload folder and public path are defined
- [ ] Instant Previews are working
