### ISSUE TITLE
New starter submission

### ISSUE THREAD

**Issue by ochollah** [forestryio/forestry.io#168]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry:

```
name: # name of your starter 
preview:# URL of your starter live preview 
image: # Thumbnail URL
author: # name of the starter's author
  versions:
  - name: # SSG name (Gatsby, Gridsome, Hugo, Jekyll, VuePress, Next, Nuxt, etc.)
    repo: # public repo URL (https://github.com/username/repo
    branch: (optional) # e.g. forestry
  textline: # short description (blog, landing page, documentation, portfolio)
```

### Submission checklist 

Make sure to setup up things in Forestry:

- [x] Import is complete 
- [x] Sidebar sections are visible 
- [x] Media upload folder and public path are defined
- [x] Instant Previews are working
