### ISSUE TITLE
New starter submission

### ISSUE THREAD

**Issue by Narno** [forestryio/forestry.io#170]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry:

```
name: The butler
preview: https://demo.cecil.app/
image: https://raw.githubusercontent.com/Cecilapp/starter-blog/master/static/images/cecil-preview.png
author: Arnaud Ligny
  versions:
  - name: Cecil
    repo: https://github.com/Cecilapp/starter-blog
    branch: master
  textline: A ready to use static blog, powered by Cecil and Hyde.
```

### Submission checklist 

Make sure to setup up things in Forestry:

- [x] Import is complete 
- [x] Sidebar sections are visible 
- [x] Media upload folder and public path are defined
- [x] Instant Previews are working
