### ISSUE TITLE
New starter submission

### ISSUE THREAD

**Issue by samuelhorn** [forestryio/forestry.io#181]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry, since you finalized the Forestry config for me 😄 

```
name: # Jamdocs
preview:# https://jamdocs.netlify.com/
author: # Samuel Horn af Rantzien
  versions:
  - name: Gridsome
    repo: https://github.com/samuelhorn/jamdocs
    branch: master
  textline: The ultimate static generated documentation theme for the JAM-stack. Highly customizable, based on Gridsome, preconfigured for Forestry, ready to deploy to Netlify in one click
```
