### ISSUE TITLE
New starter submission

### ISSUE THREAD

**Issue by mehedi-sharif** [forestryio/forestry.io#185]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry:

```
name: # Meghna 
preview:# http://demo.themefisher.com/meghna-hugo/en/
image: # https://gethugothemes.com/wp-content/uploads/edd/2019/07/Megna.jpg
author: # Themefisher
  versions:
  - name: Hugo
    repo: # https://github.com/themefisher/meghna-hugo
    branch: master
  textline: # Onepage Business Hugo Theme
```

### Submission checklist 

Make sure to setup up things in Forestry:

- [ ] Import is complete 
- [ ] Sidebar sections are visible 
- [ ] Media upload folder and public path are defined
- [ ] Instant Previews are working
