### ISSUE TITLE
 themefisher / kross-hugo 

### ISSUE THREAD

**Issue by ghost** [forestryio/forestry.io#186]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry:

```
name: Kross
preview: https://themes.gohugo.io/theme/kross-hugo-portfolio-template/
image: https://d33wubrfki0l68.cloudfront.net/0cc5d95c5befca16a8f14b0d67197c5c1696db46/c2737/kross-hugo-portfolio-template/screenshot-kross-hugo-portfolio-template_hua1726dc50382dc8979d1f90fa43be446_229423_1500x1000_fill_catmullrom_top_2.png
author: Themefisher
  versions:
  - name: Hugo
    repo:https://github.com/themefisher/kross-hugo-portfolio-template
    branch: (optional) # e.g. forestry
  textline: Portfolio
```

### Submission checklist 

Make sure to setup up things in Forestry:

- [x] Import is complete 
- [x] Sidebar sections are visible 
- [x] Media upload folder and public path are defined
- [x] Instant Previews are working
