### ISSUE TITLE
Docs: Fields Color Picker

### ISSUE THREAD

**Issue by cyrilf** [forestryio/forestry.io#191]
In a `front_matter/templates` config file I used a color picker field.

At first I used it that way:

```
- name: backgroundColor
  type: color
  label: Background color
  description: Site main background color
 ```

but this resulted in a javascript error in the forestry backend when I wanted to use the color picker.
I don't remember the exact error message but it was mentioning the `colorFormat`.

So I updated my config to add the `config` block:

```
- name: backgroundColor
  type: color
  label: Background color
  description: Site main background color
  config:
    color_format: RGB
```

now everything works.

----

- It could be **cool** to mention in the docs that the `config/color_format` key is required.
- It could be even **cooler** to default `config/color_format` to `HEX` by default in your code (or RGB, I don't care :v:) so that as a user we don't need to.

**Comment by DirtyF** [comment]
Thanks for the feedback, the format is indeed required and defaults to HEX by default. 

Here's a full example of what is generated when you create a color picker field in Forestry:

```
- name: background_color
  type: color
  label: background_color
  config:
    required: true
    color_format: Hex
  default: "#9B9B9B"
```
