### ISSUE TITLE
New starter submission

### ISSUE THREAD

**Issue by stefanweidemann** [forestryio/forestry.io#237]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry:

```
name: # b1n4ry3xe project
preview:# b1n4ry3xe.github.io
image: # Thumbnail URL
author: # Stefan Weidemann
  versions:
  - name: # Hugo
    repo: # https://https://github.com/stefanweidemann/b1n4ry3xe.github.io
    branch: (main) # e.g. forestry
  textline: # landing page
```

### Submission checklist 

Make sure to setup up things in Forestry:

- [x ] Import is complete 
- [x ] Sidebar sections are visible 
- [x ] Media upload folder and public path are defined
- [x ] Instant Previews are working
