### ISSUE TITLE
New starter submission

### ISSUE THREAD

**Issue by cristianmarint** [forestryio/forestry.io#240]
👋 Hi, I'd like to submit a new theme successfully tested on Forestry:

```
name:  Sicily 
preview: https://sicily-hugo-theme.netlify.app/
image: https://raw.githubusercontent.com/cristianmarint/sicily-hugo-theme/master/images/forestry.io.png
author: Cristian Marin
  versions:
  - name: Hugo
    repo: https://github.com/cristianmarint/sicily-hugo-theme
    branch: master
  textline: Blog
```

### Submission checklist 

Make sure to setup up things in Forestry:

- [x] Import is complete 
- [x] Sidebar sections are visible 
- [x] Media upload folder and public path are defined
- [x] Instant Previews are working
